version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore"
    include: "scope"
  cooldown:
    default-days: 7
- package-ecosystem: nix
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "chore"
    include: "scope"
  groups:
    emacs-snapshots:
      patterns:
        - "emacs-snapshot"
        - "emacs-release-snapshot"
