# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  emacs-23-4 = {
    pname = "emacs-23-4";
    version = "23.4";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-23.4.tar.gz";
      sha256 = "064w503hc5wm4b3yya9h2jmgjbw6p8p7fci0gmwiyxsj811vi8mr";
    };
  };
  emacs-24-1 = {
    pname = "emacs-24-1";
    version = "24.1";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-24.1.tar.gz";
      sha256 = "1awbgkwinpqpzcn841kaw5cszdn8sx6jyfp879a5bff0v78nvlk0";
    };
  };
  emacs-24-2 = {
    pname = "emacs-24-2";
    version = "24.2";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-24.2.tar.gz";
      sha256 = "0mykbg5rzrm2h4805y4nl5vpvwx4xcmp285sbr51sxp1yvgr563d";
    };
  };
  emacs-24-3 = {
    pname = "emacs-24-3";
    version = "24.3";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-24.3.tar.gz";
      sha256 = "0hggksbn9h5gxmmzbgzlc8hgl0c77simn10jhk6njgc10hrcm600";
    };
  };
  emacs-24-4 = {
    pname = "emacs-24-4";
    version = "24.4";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-24.4.tar.gz";
      sha256 = "1iicqcijr56r7vxxm3v3qhf69xpxlpq7afbjr6h6bpjsz8d4yg59";
    };
  };
  emacs-24-5 = {
    pname = "emacs-24-5";
    version = "24.5";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-24.5.tar.gz";
      sha256 = "1dn3jx1dph5wr47v97g0fhka9gcpn8pnzys7khp9indj5xiacdr7";
    };
  };
  emacs-25-1 = {
    pname = "emacs-25-1";
    version = "25.1";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-25.1.tar.gz";
      sha256 = "0rqw9ama0j5b6l4czqj4wlf21gcxi9s18p8cx6ghxm5l1nwl8cvn";
    };
  };
  emacs-25-2 = {
    pname = "emacs-25-2";
    version = "25.2";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-25.2.tar.gz";
      sha256 = "0b9dwx6nxzflaipkgml4snny2c3brgy0py6h05q995y1lrpbsnsh";
    };
  };
  emacs-25-3 = {
    pname = "emacs-25-3";
    version = "25.3";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-25.3.tar.gz";
      sha256 = "1jc3g79nrcix0500kiw6hqpql82ajq0xivlip6iaryxn90dnlb7p";
    };
  };
  emacs-26-1 = {
    pname = "emacs-26-1";
    version = "26.1";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-26.1.tar.gz";
      sha256 = "18vaqn7y7c39as4bn95yfcabwvqkw6y59xz8g78d1ifdx3aq40vn";
    };
  };
  emacs-26-2 = {
    pname = "emacs-26-2";
    version = "26.2";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-26.2.tar.gz";
      sha256 = "1sxl0bqwl9b62nswxaiqh1xa61f3hng4fmyc69lmadx770mfb6ag";
    };
  };
  emacs-26-3 = {
    pname = "emacs-26-3";
    version = "26.3";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-26.3.tar.gz";
      sha256 = "14bm73758w6ydxlvckfy9nby015p20lh2yvl6pnrjz0k93h4giq9";
    };
  };
  emacs-27-1 = {
    pname = "emacs-27-1";
    version = "27.1";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-27.1.tar.gz";
      sha256 = "1nw4lpid1kqncypa9f1228d43m59qn3gqgmy3vrjrfair4fsdgzz";
    };
  };
  emacs-27-2 = {
    pname = "emacs-27-2";
    version = "27.2";
    src = fetchurl {
      url = "mirror://gnu/emacs/emacs-27.2.tar.gz";
      sha256 = "0wyv7l3skbv8zvwyxnmid8b0l3kcba8xdk2df266s2kkzcc63zw0";
    };
  };
}
